[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
name = "firemerge"
description = "Firefly merge/import GUI"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "selenium ~= 4.25.0",
    "aiohttp ~= 3.10.0",
    "python-dotenv ~= 1.0.0",
    "pydantic ~= 2.9.0",
    "tzlocal ~= 5.2",
    "thefuzz ~= 0.22.0",
    "pdfplumber ~= 0.11.6",
    "click ~= 8.1.8",
]

[project.optional-dependencies]
dev = [
    "mypy==1.11",
]

[tool.setuptools]
packages = ["firemerge"]

[project.scripts]
firemerge = "firemerge.main:cli"

[tool.mypy]
plugins = [
  "pydantic.mypy"
]