[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FireMerge"
description = "Firefly merge/import GUI"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "selenium ~= 4.25.0",
    "aiohttp ~= 3.10.0",
    "python-dotenv ~= 1.0.0",
    "tomlkit ~= 0.13.0",
]

[tool.setuptools]
packages = ["firemerge"]

[project.scripts]
firemerge-scrape = "firemerge.scrape:main"
firemerge = "firemerge.web:main"